version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: bookstore:my_first_image
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

volumes:
      postgres_data:
